# Generated by Django 4.2.4 on 2023-09-09 04:30

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='GoodCrmType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_name', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='GoodMatrixType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix_name', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='PrintGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=0, max_length=7)),
                ('name', models.CharField(max_length=255)),
                ('options', models.SmallIntegerField(default=1)),
                ('layout', models.CharField(blank=True, default='', max_length=120)),
                ('pattern_file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='files/patterns'), upload_to='')),
                ('item_width', models.DecimalField(decimal_places=3, default=39, max_digits=7)),
                ('item_height', models.DecimalField(decimal_places=3, default=39, max_digits=7)),
                ('item_width_initial', models.DecimalField(decimal_places=3, default=39, max_digits=7)),
                ('item_height_initial', models.DecimalField(decimal_places=3, default=39, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='PrintType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_id', models.CharField(max_length=10)),
                ('pantone', models.CharField(default='', max_length=20)),
                ('color_name', models.CharField(max_length=60)),
                ('color_code', models.CharField(max_length=7)),
                ('color_scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing_report.colorscheme')),
            ],
        ),
    ]
