# Generated by Django 4.2.4 on 2023-09-16 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_report', '0003_customertypes_customergroups_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('item_name', models.CharField(blank=True, max_length=20, null=True)),
                ('eco', models.BooleanField(default=True)),
                ('detail1_name', models.CharField(max_length=60)),
                ('detail1_place', models.BooleanField(default=False)),
                ('detail2_name', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('detail2_place', models.BooleanField(default=False)),
                ('detail3_name', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('detail3_place', models.BooleanField(default=False)),
                ('detail4_name', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('detail4_place', models.BooleanField(default=False)),
                ('detail5_name', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('detail5_place', models.BooleanField(default=False)),
                ('detail6_name', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('detail6_place', models.BooleanField(default=False)),
                ('color_scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing_report.colorscheme')),
                ('crm', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing_report.goodcrmtype')),
                ('matrix', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing_report.goodmatrixtype')),
                ('print_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing_report.printgroup')),
            ],
        ),
    ]
