# Generated by Django 4.2.4 on 2023-10-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_report', '0008_importcustomers'),
    ]

    operations = [
        migrations.AddField(
            model_name='importcustomers',
            name='changes',
            field=models.BooleanField(default=True),
        ),
    ]
