# Generated by Django 4.2.4 on 2023-10-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_report', '0009_importcustomers_changes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importcustomers',
            old_name='changes',
            new_name='changed',
        ),
        migrations.AddField(
            model_name='importcustomers',
            name='new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='importcustomers',
            name='region',
            field=models.CharField(blank=True, default='', max_length=2, null=True),
        ),
    ]
