# Generated by Django 4.2.4 on 2024-02-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_report', '0011_customer_new_importcustomers_internal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importcustomers',
            name='changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='importcustomers',
            name='new',
            field=models.BooleanField(default=False),
        ),
    ]
