# Generated by Django 4.2.4 on 2024-02-04 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_report', '0013_rename_scheme_name_colorscheme_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='color_id',
            new_name='code',
        ),
    ]
