# Generated by Django 4.2.4 on 2024-02-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_report', '0014_rename_color_id_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='standard',
            field=models.BooleanField(default=True),
        ),
    ]
