# Generated by Django 4.2.4 on 2024-02-04 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_report', '0015_color_standard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='color_name',
            new_name='name',
        ),
    ]
