# Generated by Django 4.2.4 on 2024-02-10 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_report', '0015_salesperiod_salesperiodbusinessunit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesperiodbusinessunit',
            name='salesperiod_ptr',
        ),
        migrations.AddField(
            model_name='salesperiodbusinessunit',
            name='average_check',
            field=models.FloatField(default=0, null=True, verbose_name='средний чек'),
        ),
        migrations.AddField(
            model_name='salesperiodbusinessunit',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesperiodbusinessunit',
            name='period',
            field=models.ForeignKey(default=603, on_delete=django.db.models.deletion.CASCADE, to='marketing_report.reportperiod'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesperiodbusinessunit',
            name='total_no_sales',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='количество продаж'),
        ),
        migrations.AddField(
            model_name='salesperiodbusinessunit',
            name='total_profit',
            field=models.FloatField(default=0, null=True, verbose_name='прибыль'),
        ),
        migrations.AddField(
            model_name='salesperiodbusinessunit',
            name='total_quantity',
            field=models.IntegerField(default=0, verbose_name='количество'),
        ),
        migrations.AddField(
            model_name='salesperiodbusinessunit',
            name='total_sales_with_vat',
            field=models.FloatField(default=0, null=True, verbose_name='продажи с НДС'),
        ),
        migrations.AddField(
            model_name='salesperiodbusinessunit',
            name='total_sales_without_vat',
            field=models.FloatField(default=0, null=True),
        ),
    ]
