# Generated by Django 4.2.4 on 2024-02-04 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_report', '0016_rename_color_name_color_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='printtype',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='printtype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='printtype',
            name='name',
        ),
        migrations.AddField(
            model_name='printtype',
            name='settingsdictionary_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='marketing_report.settingsdictionary'),
            preserve_default=False,
        ),
    ]
