# Generated by Django 4.2.4 on 2024-02-04 12:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportCustomers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frigat_id', models.IntegerField(db_index=True)),
                ('form', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('inn', models.CharField(max_length=20, null=True)),
                ('region', models.CharField(blank=True, default='', max_length=2, null=True)),
                ('customer_type', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('all_phones', models.CharField(blank=True, max_length=600, null=True)),
                ('mail', models.CharField(blank=True, max_length=255, null=True)),
                ('all_mails', models.CharField(blank=True, max_length=600, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('our_manager', models.CharField(blank=True, max_length=255)),
                ('changed', models.BooleanField(default=False)),
                ('new', models.BooleanField(default=False)),
                ('internal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReportPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('MT', 'месяц'), ('QT', 'квартал'), ('YR', 'год')], default='MT', max_length=2)),
                ('date_begin', models.DateField(default=datetime.date(2000, 1, 1))),
                ('date_end', models.DateField(default=datetime.date(2000, 1, 31))),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SettingsDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ColorScheme',
            fields=[
                ('settingsdictionary_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='marketing_report.settingsdictionary')),
            ],
            bases=('marketing_report.settingsdictionary',),
        ),
        migrations.CreateModel(
            name='CrmType',
            fields=[
                ('settingsdictionary_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='marketing_report.settingsdictionary')),
            ],
            bases=('marketing_report.settingsdictionary',),
        ),
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('settingsdictionary_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='marketing_report.settingsdictionary')),
                ('group_discount', models.FloatField(default=0)),
                ('code', models.CharField(default='', max_length=2)),
            ],
            bases=('marketing_report.settingsdictionary',),
        ),
        migrations.CreateModel(
            name='MatrixType',
            fields=[
                ('settingsdictionary_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='marketing_report.settingsdictionary')),
            ],
            bases=('marketing_report.settingsdictionary',),
        ),
        migrations.CreateModel(
            name='PrintType',
            fields=[
                ('settingsdictionary_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='marketing_report.settingsdictionary')),
            ],
            bases=('marketing_report.settingsdictionary',),
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('settingsdictionary_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='marketing_report.settingsdictionary')),
                ('item_code', models.CharField(blank=True, max_length=20, null=True)),
                ('eco', models.BooleanField(default=True)),
                ('multicolor', models.BooleanField(default=False)),
                ('date_first', models.DateField(default=datetime.date(2000, 1, 1))),
                ('date_last', models.DateField(default=datetime.date(2000, 1, 1))),
                ('color_scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing_report.colorscheme')),
                ('crm_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing_report.crmtype')),
                ('matrix_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing_report.matrixtype')),
            ],
            bases=('marketing_report.settingsdictionary',),
        ),
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('settingsdictionary_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='marketing_report.settingsdictionary')),
                ('phone', models.CharField(default='', max_length=255)),
                ('mail', models.CharField(default='', max_length=255)),
                ('date_first', models.DateField(default=datetime.date(2000, 1, 1))),
                ('date_last', models.DateField(default=datetime.date(2000, 1, 1))),
                ('active', models.BooleanField(default=True)),
                ('customer_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing_report.customertype')),
            ],
            bases=('marketing_report.settingsdictionary',),
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('settingsdictionary_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='marketing_report.settingsdictionary')),
                ('code', models.CharField(max_length=10)),
                ('pantone', models.CharField(default='', max_length=20)),
                ('color_code', models.CharField(max_length=7)),
                ('date_first', models.DateField(default=datetime.date(2000, 1, 1))),
                ('date_last', models.DateField(default=datetime.date(2000, 1, 1))),
                ('standard', models.BooleanField(default=True)),
                ('color_scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing_report.colorscheme')),
            ],
            bases=('marketing_report.settingsdictionary',),
        ),
    ]
