# Generated by Django 4.2.4 on 2023-09-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_report', '0004_goods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='detail1_name',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='detail1_place',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='detail2_name',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='detail2_place',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='detail3_name',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='detail3_place',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='detail4_name',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='detail4_place',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='detail5_name',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='detail5_place',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='detail6_name',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='detail6_place',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='print_group',
        ),
        migrations.AddField(
            model_name='goods',
            name='multicolor',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PrintGroup',
        ),
    ]
