# Generated by Django 4.2.4 on 2024-02-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_report', '0004_rename_frigat_id_customer_frigat_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='frigat_code',
            field=models.CharField(db_index=True, default='', max_length=30, unique=True),
        ),
    ]
