# Generated by Django 4.2.4 on 2023-09-17 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_report', '0005_remove_goods_detail1_name_remove_goods_detail1_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='date_first',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AddField(
            model_name='color',
            name='date_last',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AddField(
            model_name='goods',
            name='date_first',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AddField(
            model_name='goods',
            name='date_last',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
