# Generated by Django 4.2.4 on 2024-02-07 14:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_report', '0006_importcustomers_import_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_date', models.DateField(default=datetime.date(2024, 1, 31))),
                ('code', models.CharField(max_length=140)),
                ('color_code', models.CharField(max_length=60, null=True)),
                ('main_color', models.CharField(max_length=60, null=True)),
                ('quantity', models.FloatField(default=0)),
                ('sales_doc_no', models.CharField(max_length=20, null=True)),
                ('sales_doc_date', models.DateField(default=datetime.date(2019, 1, 1))),
                ('purchase_without_vat', models.FloatField(default=0)),
                ('purchase_with_vat', models.FloatField(default=0)),
                ('sale_without_vat', models.FloatField(default=0)),
                ('sale_with_vat', models.FloatField(default=0)),
                ('price_vat', models.FloatField(default=0)),
                ('customer_frigat_id', models.IntegerField(null=True)),
                ('customer_name', models.CharField(max_length=255, null=True)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing_report.color')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing_report.customer')),
                ('goods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing_report.goods')),
            ],
        ),
    ]
