# Generated by Django 4.2.4 on 2024-02-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_report', '0007_importsales'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsales',
            name='no_vat',
            field=models.BooleanField(default=False),
        ),
    ]
