# Generated by Django 4.2.4 on 2024-02-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_report', '0008_importsales_no_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsales',
            name='profit',
            field=models.FloatField(default=0),
        ),
    ]
