# Generated by Django 4.2.4 on 2023-10-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_report', '0010_rename_changes_importcustomers_changed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='importcustomers',
            name='internal',
            field=models.BooleanField(default=False),
        ),
    ]
