# Generated by Django 4.2.4 on 2024-02-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_report', '0011_rename_sales_doc_number_salesdoc_sales_doc_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestransactions',
            name='eco',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salestransactions',
            name='good_no_error',
            field=models.BooleanField(default=True),
        ),
    ]
