# Generated by Django 4.2.4 on 2024-02-10 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_report', '0014_remove_salesdoc_eco_remove_salestransactions_eco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.IntegerField(default=0, verbose_name='количество')),
                ('total_sales_without_vat', models.FloatField(default=0, null=True)),
                ('total_sales_with_vat', models.FloatField(default=0, null=True, verbose_name='продажи с НДС')),
                ('total_profit', models.FloatField(default=0, null=True, verbose_name='прибыль')),
                ('total_no_sales', models.SmallIntegerField(default=0, null=True, verbose_name='количество продаж')),
                ('average_check', models.FloatField(default=0, null=True, verbose_name='средний чек')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing_report.reportperiod')),
            ],
        ),
        migrations.CreateModel(
            name='SalesPeriodBusinessUnit',
            fields=[
                ('salesperiod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='marketing_report.salesperiod')),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing_report.businessunit')),
            ],
            bases=('marketing_report.salesperiod',),
        ),
    ]
