# Generated by Django 4.2.4 on 2024-02-10 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_report', '0017_customergroup_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='frigat_code',
            new_name='frigate_code',
        ),
        migrations.RenameField(
            model_name='importcustomers',
            old_name='frigat_id',
            new_name='frigate_code',
        ),
        migrations.RenameField(
            model_name='salesdoc',
            old_name='customer_frigat_id',
            new_name='customer_frigate_id',
        ),
        migrations.RenameField(
            model_name='salestransactions',
            old_name='customer_frigat_id',
            new_name='customer_frigate_id',
        ),
        migrations.CreateModel(
            name='CustomerGroupFrigateId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frigate_code', models.CharField(max_length=140, unique=True)),
                ('customer_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing_report.customergroup')),
            ],
        ),
    ]
