# Generated by Django 4.2.4 on 2024-02-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_report', '0018_rename_frigat_code_customer_frigate_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customergroupfrigateid',
            name='frigate_code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='importcustomers',
            name='frigate_code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='salesdoc',
            name='customer_frigate_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='salestransactions',
            name='customer_frigate_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
