# Generated by Django 4.2.4 on 2024-02-11 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_report', '0020_customerperiodbyunit_customerperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesperiodbusinessunit',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing_report.businessunit'),
        ),
    ]
