# Generated by Django 4.2.4 on 2024-02-11 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_report', '0022_alter_goodsperiod_good'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerperiodbyunit',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing_report.businessunit'),
        ),
    ]
