# Generated by Django 4.2.4 on 2024-02-14 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_report', '0023_alter_customerperiodbyunit_business_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsperiod',
            old_name='sale_with_vat',
            new_name='sales_with_vat',
        ),
        migrations.RenameField(
            model_name='goodsperiod',
            old_name='sale_without_vat',
            new_name='sales_without_vat',
        ),
    ]
