# Generated by Django 4.2.4 on 2024-02-17 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_report', '0024_rename_sale_with_vat_goodsperiod_sales_with_vat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FedRegion',
            fields=[
                ('settingsdictionary_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='marketing_report.settingsdictionary')),
            ],
            bases=('marketing_report.settingsdictionary',),
        ),
        migrations.CreateModel(
            name='TypeGroup',
            fields=[
                ('settingsdictionary_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='marketing_report.settingsdictionary')),
            ],
            bases=('marketing_report.settingsdictionary',),
        ),
        migrations.CreateModel(
            name='RegionToFedRegion',
            fields=[
                ('settingsdictionary_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='marketing_report.settingsdictionary')),
                ('fed_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing_report.fedregion')),
            ],
            bases=('marketing_report.settingsdictionary',),
        ),
        migrations.AddField(
            model_name='customer',
            name='fed_region',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing_report.fedregion'),
        ),
        migrations.AddField(
            model_name='customertype',
            name='type_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing_report.typegroup'),
        ),
    ]
