# Generated by Django 4.2.4 on 2024-02-17 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_report', '0025_fedregion_typegroup_regiontofedregion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customergroup',
            name='fed_region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing_report.fedregion'),
        ),
    ]
