# Generated by Django 4.2.4 on 2024-03-02 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_report', '0027_customerarea_customer_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='area',
            new_name='customer_area',
        ),
    ]
