from marketing_report.models.settings_dictionary import SettingsDictionary
from marketing_report.models.color_models import *
from marketing_report.models.customer_group_models import *
from marketing_report.models.customer_models import *
from marketing_report.models.goods_types_models import *
from marketing_report.models.goods_models import *
from marketing_report.models.import_models import *
from marketing_report.models.report_period import *
from marketing_report.models.sales import *
from marketing_report.models.sales_period import *
from marketing_report.models.goods_periods import *
from marketing_report.models.customer_periods import *
